on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

name: tests

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir/OTP ${{matrix.elixirbase}}
    strategy:
      fail-fast: false
      matrix:
        elixirbase:
        - 1.13.0-erlang-22.3.4.2-alpine-3.12.0
        - 1.14.5-erlang-24.3.4.15-alpine-3.18.4
        - 1.16.0-erlang-26.2.1-alpine-3.17.5
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Earthly
        uses: earthly/actions-setup@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests under ${{matrix.elixirbase}}
        run: earthly -P --ci --build-arg ELIXIR_BASE=${{matrix.elixirbase}} --build-arg COVERALLS_GITHUB=true +test