on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

name: tests

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        elixirbase:
        - 1.9.4-erlang-20.3.8.26-alpine-3.11.6
        - 1.11.3-erlang-23.2.7.5-alpine-3.16.0
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Earthly
        uses: earthly/actions-setup@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests under ${{matrix.elixirbase}}
        run: earthly -P --ci --build-arg ELIXIR_BASE=${{matrix.elixirbase}} +test